services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.7.8
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    networks:
      - homeassistant
    restart: always
    environment:
      INFLUXDB_DB: "db0" 
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      INFLUXDB_USER: ${INFLUXDB_USER}
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD}
      TZ: ${TIMEZONE}

  grafana:
    container_name: grafana
    depends_on:
      - influxdb
    image: grafana/grafana:latest
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    links:
      - influxdb
    networks:
      - homeassistant
    restart: always
    environment:
      TZ: ${TIMEZONE}
      GF_SERVER_ROOT_URL: https://domain.example.com
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./mariadb:/etc/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
      - "3306:3306"
    networks:
      - homeassistant
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ha
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TIMEZONE}

  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - homeassistant
    environment:
      PMA_ABSOLUTE_URI: https://pma.example.com
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TIMEZONE}
      PMA_HOST: mariadb

  chronograf:
    container_name: chronograf
    image: chronograf
    volumes:
      - ./chronograf:/var/lib/chronograf
    ports:
      - 8888:8888
    links:
      - influxdb
    networks:
      - homeassistant
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}

volumes:
  db_conf:
      driver: local

networks:
  homeassistant:
    name: homeassistant
    external: true
