services: 
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data  
    ports:
    - 9000:9000
    networks:
      - homeassistant
    restart: always
    environment:
      - TZ=$TIMEZONE
      
  emqx:
    container_name: emqx
    image: emqx/emqx:latest
    volumes:
      - ./emqx_data:/opt/emqx/data
      - ./emqx_log:/opt/emqx/log
    network_mode: host
    restart: always
    environment:
      - TZ=$TIMEZONE

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:$HA_VER
    volumes:
      - ./ha_config:/config
      - /etc/localtime:/etc/localtime:ro
    #network_mode: host
    ports:
     - 8123:8123
    privileged: true
    depends_on:
      - emqx
    restart: always
    environment:
      - TZ=$TIMEZONE

 
  nodered:
    container_name: nodered
    image: nodered/node-red:$NR_VER
    volumes:
      - ./node-red:/data
      - /etc/localtime:/etc/localtime:ro 
      - /etc/timezone:/etc/timezone:ro
    ports:
    - 1880:1880
    networks:
      - homeassistant
    restart: always
    environment:
      - TZ=$TIMEZONE

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:$Z2M_VER
    volumes:
      - ./zigbee2mqtt:/app/data
    #expose:
    #  - "8888"
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    privileged: true 
    restart: always
    networks:
      - homeassistant
    environment:
      - TZ=$TIMEZONE

networks:
  homeassistant:
    name: homeassistant
    external: true